SET ANSI_PADDING,CONCAT_NULL_YIELDS_NULL,
  ANSI_WARNINGS,ARITHABORT,ANSI_NULLS,
  QUOTED_IDENTIFIER ON
SET NUMERIC_ROUNDABORT OFF

GO

CREATE   VIEW Z_ACTIVE_ITEMS WITH SCHEMABINDING
AS
SELECT item_no
FROM imitmidx_sql
WHERE activity_cd = 'A'

GO

CREATE UNIQUE CLUSTERED Index ACTIVE_ITEMS_INDEX ON Z_ACTIVE_ITEMS
  (item_no)
Go
